### ISSUE TITLE
Partial fill trade updates should contain the most recent partial fill quantity

### ISSUE THREAD

**Issue by garrett-davidson** [alpacahq/Alpaca-API#103]
I previously [asked about this on the forums](https://forum.alpaca.markets/t/getting-quantities-on-partial-fills/667) and got no response. Currently when one receives a partial fill trade update from the streaming API, they learn information about the totality of their order, but not about that specific partial fill.

For day trading this isn't tenable, because I want to have the option to turn the asset around the moment any part of the order fills. I have a detailed example in the above linked forum post. Basically, I'd like to see a field on the `fill` and `partial_fill` trade events which contains the quantity that was filled _for that update_. This way, if I have a buy for 10,000 shares that takes several partial fills to complete, I have the option turn around and open a sell each time there's a partial fill for whatever amount was recently filled, without needing to try to keep track of that manually.

**Comment by umitanuki** [comment]
Sounds like a good idea, let us take a look at it. Also suggested a workaround in the forum.

**Comment by Neal** [comment]
@garrett-davidson thanks for the suggestion - the (partial) fill trade update message now includes a `qty` field which equals to the quantity of shares filled in that update along with `price` which equals to the price it was filled at.

**Comment by garrett-davidson** [comment]
Wow, that was so fast! Thanks everyone!
