### ISSUE TITLE
Trading via Oauth account fails

### ISSUE THREAD

**Issue by WhatIsTofu** [alpacahq/Alpaca-API#106]
An account that was authorized with the following scopes, `scope=account:write%20trading` fails to place a trade with the following error: `Failed to authorize current action`. The returned scope is 
`scope: 'account:write trading data' `. Are there any additional steps that is required to be authorized?

Thank you :pray:

**Comment by lvca** [comment]
@Neal what are whose steps? This morning it failed to me to buy stocks with this error:

```
Error on retrieving json from POST URL 'https://api.alpaca.markets/v2/orders' posting {"symbol":"SQQQ","side":"buy","time_in_force":"day","extended_hours":true,"qty":"333","type":"limit","limit_price":"25.81"} (error={"code":40110000,"message":"token is not authorized for this scope"})

``

I've always used `account:write%20trading` for scope.

This is the popup about my app on the website:

![image](https://user-images.githubusercontent.com/312606/76238690-3c54cf80-61fe-11ea-9183-572f01a8507d.png)

**Comment by Neal** [comment]
@lvca is your app approved for live trading? You can check that if you go to your app on https://app.alpaca.markets/brokerage/apps/manage and it should say something at the bottom about how to enable live trading.

**Comment by lvca** [comment]
Do you mean this? 
![image](https://user-images.githubusercontent.com/312606/76257207-44713700-621f-11ea-86ae-edcf541648aa.png)

**Comment by Neal** [comment]
Under `My Developed Apps`. `My Connected Apps` are the apps you've authorized.

**Comment by lvca** [comment]
Is it this? 

![image](https://user-images.githubusercontent.com/312606/76258904-73d57300-6222-11ea-861a-42f0b0f22b6d.png)

But I've used the token for weeks. Why changing policy now?

**Comment by Neal** [comment]
Yes. Have you used it for live trading? If your app isn't approved for live trading, it couldn't have worked for live trading. This is not a new policy.

**Comment by lvca** [comment]
Yes, I've traded for at least 2 weeks with the new token without problems. Anyway, I've just sent the request via email.

**Comment by Neal** [comment]
We can look into it more but there has been no code change around this for a while and this policy has existed since we launched OAuth.
