### ISSUE TITLE
Status of order will always return as "accepted" even tho it is rejected

### ISSUE THREAD

**Issue by Xatnagh** [alpacahq/Alpaca-API#107]
I just started doing this today and is following the step by step tutorial on your website:https://docs.alpaca.markets/get-started-with-alpaca/tutorial-videos/   
(first video)
When i got to the order section, I successfully created a order and have it show up in the overview page, but since market is closed right now, the order didn't get filled, hence rejected.
But when I print out the status of the order, it shows as accepted.

**Comment by umitanuki** [comment]
Did you get the latest order status from List Orders API? When you receive the order entity from Submit Order API (POST), its status is "accepted", yes, but the status change to "rejected" is asynchronous.
