### ISSUE TITLE
{"stream":"trade_updates","data":null}

### ISSUE THREAD

**Issue by d-e-s-o** [alpacahq/Alpaca-API#110]
For a few days now I see trade updates without any data.
```
{"stream":"trade_updates","data":null}
```

Mind fixing this regression and adding a test?

**Comment by ZippeyKeys12** [comment]
Guessing this was a temporary issue?

**Comment by d-e-s-o** [comment]
No offense, but I don't really care what you guess. We are supposed to be engineers and not fortunetellers. So either this has been root caused, explained, and fixed or it hasn't. Since I don't see any explanation here it's the latter.

**Comment by ZippeyKeys12** [comment]
If you find that it repeats, then there's reason for concern and you should reopen this issue. Otherwise there's no information in this issue. Was it over an extended period of time? Did it occur continuously or was it sporadic?

**Comment by d-e-s-o** [comment]
> If you find that it repeats, then there's reason for concern and you should reopen this issue.

The biggest concern is how long it takes Alpaca to look at issues, followed directly by the fact that they are brushed off as "temporary".

> Otherwise there's no information in this issue. Was it over an extended period of time? Did it occur continuously or was it sporadic?

I saw the issue over a period of a couple of days, sporadically.

**Comment by ZippeyKeys12** [comment]
I hear you, it's just that if the problem is no longer producible, it isn't really possible to determine whether it's been fixed or not, unless it repeats.

We're working to streamline the process, so that issues can be effectively addressed and resolved.
