### ISSUE TITLE
Access key verification failed (Code = 40110000)

### ISSUE THREAD

**Issue by GarryWalsh** [alpacahq/Alpaca-API#118]
My paper api has been working flawlessly for a few months now. Nothing has changed in how I have been accessing the endpoints in weeks.

Today I started experiencing this error for the bars endpoint (Possibly others too haven't tested)

{
    "code": 40110000,
    "message": "access key verification failed (Code = 40110000)"
}

Happened earlier today and regenerated my API keys and it worked fine for a few hours and now happening again

**Comment by GarryWalsh** [comment]
Seems to have been a temporary issue, the bars endpoint is working again without having to regenerate the keys.

I'm leaving this open as it is still an issue that it happened at all

**Comment by GarryWalsh** [comment]
Intermittently happening all day

**Comment by umitanuki** [comment]
We had an issue one day but it should be working fine. Let us know if you still see it.
