### ISSUE TITLE
Polygon Stock Dividends discrepancy 

### ISSUE THREAD

**Issue by kaspiton** [alpacahq/Alpaca-API#120]
When i am calling method /v2/reference/dividends/{symbol} from Polygon API by using my API key. I receive the following JSON structure:
        {
            "ticker": "AAPL",
            "exDate": "2020-05-08",
            "paymentDate": "2020-05-14",
            "recordDate": "2020-05-11",
            "amount": 0.82
        }
While I see that on the Polygon website in the API documentation the JSON structure is different, it is more expanded:
    {
      "symbol": "AAPL",
      "type": "Dividend income",
      "exDate": "2016-11-03T04:00:00.000Z",
      "paymentDate": "2016-11-03T04:00:00.000Z",
      "recordDate": "2016-11-03T04:00:00.000Z",
      "declaredDate": "2016-11-03T04:00:00.000Z",
      "amount": 0.57,
      "qualified": "Q",
      "flag": "YE"
    }
What there is such a difference or am I doing anything wrong?

Thank you

**Comment by ZippeyKeys12** [comment]
This would be a question for Polygon
