### ISSUE TITLE
Why i cannot pull information regarding following stock OGZPY?

### ISSUE THREAD

**Issue by kaspiton** [alpacahq/Alpaca-API#121]
Hello,

Can anyone advise on the following? The stock belongs to Gasprom:
**Request:**
https://api.alpaca.marketsets/v2/assets/OGZPY
**Response:**
{
    "code": 40410000,
    "message": "asset not found for OGZPY"
}

While on other platforms I can get information regarding this stock?

Thank you

**Comment by umitanuki** [comment]
This stock is not supported. Alpaca supports US-listed stocks only.
