### ISSUE TITLE
alpaca API connection issues

### ISSUE THREAD

**Issue by leoindman** [alpacahq/Alpaca-API#123]
Hello,

All day today I've been having connection issues with the alpaca API through python. I've been trading fine all the days before and haven't made impactful updates to my code. Today for some reason lots of connection issues randomly occurring for both the live and paper accounts. Here is an example:

requests.exceptions.HTTPError: 502 Server Error: Bad Gateway for url: https://data.alpaca.markets/v1/bars/minute?symbols=TSLA&limit=1

here is another one:

requests.exceptions.ConnectionError: HTTPSConnectionPool(host='data.alpaca.markets', port=443): Max retries exceeded with url: /v1/last_quote/stocks/SPY (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fb9bf5775e0>: Failed to establish a new connection: [Errno 60] Operation timed out'))

Thank you,
Leo

**Comment by ZippeyKeys12** [comment]
Appears to have been a temporary issue

**Comment by calvincolton** [comment]
I've been seeing the same issue, frequently, intermittently, the past three days. Is it a temporary issue? There are also similar reports on the forum: https://forum.alpaca.markets/t/alpaca-py-issues-max-retries-exceeded-newconnectionerror/10299

**Comment by ZippeyKeys12** [comment]
I'm not involved with Alpaca, but fyi, something being temporary doesn't mean it can't happen again. A power outage is usually temporary, but it can happen again.
