### ISSUE TITLE
/v1/bars/___ endpoint returns 404

### ISSUE THREAD

**Issue by Kalin-Rudnicki** [alpacahq/Alpaca-API#129]
- I am able to hit `/v2/accounts` just fine
- When I try to hit `/v1/bars/anyTimeFrame`, I get a 404
  - I have already tried replacing the v1 stated on the docs with v2
  - I have also tried not using `paper-`
- I get the same issue with curl and when doing it programmatically
---
- Does anyone else have this issue (if you were to try it right now)
- Am I doing something wrong? Whats the fix?
---
```
url: https://paper-api.alpaca.markets/v2/bars/1Min
headers: 
	[User-Agent : scalaj-http/2.4.2]
	[APCA-API-KEY-ID : ???]
	[APCA-API-SECRET-KEY : ???]
params: 
	[symbols : TSLA,NVDA]
	[limit : 5]
IO(throw java.lang.Error: Unexpected content found: Not Found)
```

**Comment by d-e-s-o** [comment]
Try using `https://data.alpaca.markets` as the base URL.

**Comment by Kalin-Rudnicki** [comment]
Thank you so much! That worked!! I was starting to lose hope there for a bit. I am really new to this, and it sounds like that change might have been obvious, but it would be nice if it mentioned that here: `https://alpaca.markets/docs/api-documentation/api-v2/market-data/bars/`. I don't see any reference to `data.`, just `/v1/bars/{timeframe}`.
Again, thank you!!

**Comment by d-e-s-o** [comment]
Well, it's documented on the ["parent" page](https://alpaca.markets/docs/api-documentation/api-v2/market-data/). I don't know if that's sufficient or not. Perhaps it could be moved. \*shrug\*

If you feel strongly, perhaps open a pull request and discuss with the owners. Otherwise, just close the issue.
