### ISSUE TITLE
Market data completely off

### ISSUE THREAD

**Issue by esoli9** [alpacahq/Alpaca-API#148]
The market data is completely off for all stock I've tried so far!

![AAPL](https://user-images.githubusercontent.com/75094791/103250770-2f1bf380-497e-11eb-9a16-f0c37fca79c8.png)

**To Reproduce**
`barset = api.get_barset(symbol, timeframe, start=startDate)`

where:
`symbol = 'AAPL'`
`timeframe = 'day'`
`startDate = '08-01-2020'  # MM-DD-YYYY`
 `startDate = pd.Timestamp(startDate).isoformat() + '-04:00'`

Even looking at the returned barset, the AAPL stock was never at over $400:
![Screen Shot 2020-12-28 at 6 39 53 pm](https://user-images.githubusercontent.com/75094791/103250951-30015500-497f-11eb-8af4-611dff224a0d.png)

It is the same issue for various other stock, like TSLA here: 
![tsla](https://user-images.githubusercontent.com/75094791/103250959-3bed1700-497f-11eb-8541-3b3b83609298.png)

I hope it's something (simple) that I am doing wrong... Otherwise, this is really concerning!

**Comment by d-e-s-o** [comment]
`AAPL` and `TSLA` both had stock splits in pretty much that time frame [[0]](https://markets.businessinsider.com/news/stocks/apple-stock-split-price-what-that-means-how-many-shares-2020-7-1029455711?op=1) [[1]](https://www.cnn.com/2020/08/31/investing/tesla-stock-split-trnd/index.html).

From what I understand typically APIs apply splits to past data when reporting (or make it configurable; which is probably what you are comparing against), but that does not appear to be the case here.

Edit: Also see https://github.com/alpacahq/Alpaca-API/issues/131.

**Comment by esoli9** [comment]
> `AAPL` and `TSLA` both had stock splits in pretty much that time frame [[0]](https://markets.businessinsider.com/news/stocks/apple-stock-split-price-what-that-means-how-many-shares-2020-7-1029455711?op=1) [[1]](https://www.cnn.com/2020/08/31/investing/tesla-stock-split-trnd/index.html).
> 
> From what I understand typically APIs apply splits to past data when reporting (or make it configurable; which is probably what you are comparing against), but that does not appear to be the case here.
> 
> Edit: Also see #131.

THANKS!!! This makes a lot more sense now :)
Hope the `adjusted` feature will be implemented soon....
