### ISSUE TITLE
V2 API Adjusted Historical Bars

### ISSUE THREAD

**Issue by rommladera** [alpacahq/Alpaca-API#175]
Calls to the API /v2/stocks/{symbol}/bars are not adjusted.  There should be a parameter to retrieve adjusted or unadjusted OHLC.

**Comment by cnaccio** [comment]
I second this; was using this feature when data was coming from Polygon, but now need to migrate my code and this is a problem.

**Comment by lvca** [comment]
+100. This feature is fundamental even to render a basic chart.

**Comment by tifolson** [comment]
+1 for adjusted data parameter. For both stock splits and dividends.

**Comment by tlk3** [comment]
How could have possibly been overlooked? Historical data is virtually useless otherwise.

**Comment by k-** [comment]
Can we get an update, acknowledgement, or estimate on this? As stated above, lacking this feature makes any data outside of the current trading day meaningless (or dangerous for those who aren't aware).

**Comment by haron4igg** [comment]
Bought Unlimited plan just to get data adjusted... what a surprise it is still raw...

**Comment by gnvk** [comment]
You can set the `adjustment` parameter to
- `split`: to adjust the bars after stock splits
- `dividend`: to adjust the bars after dividends
- `both`: to adjust the bars both after stock splits and dividends
- `raw`: to not adjust the bars

https://alpaca.markets/docs/api-documentation/api-v2/market-data/alpaca-data-api-v2/historical/#bars

**Comment by ovresko** [comment]
> You can set the `adjustment` parameter to
> 
> * `split`: to adjust the bars after stock splits
> * `dividend`: to adjust the bars after dividends
> * `both`: to adjust the bars both after stock splits and dividends
> * `raw`: to not adjust the bars
> 
> https://alpaca.markets/docs/api-documentation/api-v2/market-data/alpaca-data-api-v2/historical/#bars

adjustment both returns  "message": "invalid adjustment"

**Comment by ovresko** [comment]
toke a guess and found adjustement : "all" working

**Comment by highmtn** [comment]
The `adjustment` param sort of work nows. Tested on TSLA, `split`, `dividend`, and `raw` work. `dividend` does not. (Using the node Alpaca package). 

FWIW - if you're considering Alpaca, I'd avoid. The API has a bunch of headaches like this. There's no mention of this split param in their docs right now. The docs are out of date. Their support forum threads go unresponded to. They switched off of nice Polygon data sometime in 2021 and folks seem to have more complaints.
