### ISSUE TITLE
OAuth2 returns "invalid_client" error

### ISSUE THREAD

**Issue by lvca** [alpacahq/Alpaca-API#179]
**Describe the bug**
OAuth request returns `{"code":40110000,"message":"invalid_client"}` in the last hours.

**Expected behavior**
A valid JSON with the token.

**Desktop (please complete the following information):**
 - OS: MacOSX
 - Browser Safari

**Additional context**
The client id used is unchanged for 1y. Checked on my account and it matches with the one passed.

**Comment by andylebo20** [comment]
any update on this? getting same error

**Comment by captainsalt** [comment]
I am also getting the same error

**Comment by umitanuki** [comment]
The original question was resolved by adding `application/x-www-form-urlencoded` to the request header. This is per [RFC](https://tools.ietf.org/html/rfc6749#section-3.2)

If this is not the cause, please open a new issue with the details.

**Comment by mjKosmic** [comment]
I am having this issue and i have set the header
