### ISSUE TITLE
Add OAuth authentication for app integrations

### ISSUE THREAD

**Issue by codebeaulieu** [alpacahq/Alpaca-API#20]
I'm building a large mobile app that is centered around Alpaca's API and it would be awesome to authenticate users via OAuth rather than asking them to trust me with their API/Keys.

**Comment by taylorgoolsby** [comment]
+1 From me too.

___

Somewhat related note:

By the way everyone, did you know Plaid stores your bank credentials somewhere in their database, and then they just use web scraping techniques to log you in and keep your session token refreshed?

I don't use Plaid because I think that's a little crazy (and it probably violates my banks Terms of Usage thus voiding warranty). And for the same reason, I wouldn't be comfortable giving an app built on top of Alpaca my credentials.

___

Another benefit of OAuth are scopes. Not sure what scopes we need, but think of the possibility of limiting what an authorized third party could do. I think there's value in that over giving the third party your Alpaca credentials, which is nearly full access to everything.

**Comment by empireofryan** [comment]
Very eager for this feature. Will be a game-changer for Alpaca once engineers can build solutions to offer to a mass audience.

**Comment by ChemicalRocketeer** [comment]
Alpaca engineer here. I can't promise any features, but I'm personally excited to see interest! I have been interested in the idea of providing OAuth for a while now.

I have my own ideas of course, but I'd like to better understand how developers would use a hypothetical OAuth feature. We have a lot of big long-term plans for Alpaca, so if y'all wouldn't mind sharing more details of the apps you'd like to make, it would help us understand how this could possibly fit into the future of the platform.

**Comment by taylorgoolsby** [comment]
I have no idea if it's possible, but it would be nice if my end users didn't have to log into alpaca at all. Alpaca still hold their money and position, but they make their account on my app, and they link their bank through my app. I don't want to hold any of their credentials in my database. No passwords, api keys, or bank routing or bank account numbers.

Ideally, there is some kind of API to do all this onboarding via oauth.

**Comment by codebeaulieu** [comment]
@ChemicalRocketeer I'd be willing to share what I've build via email. My app already exists and I use it today, I just want to offer it in Google and Apples app stores and asking folks to share their API Key's and Secrets is not cool.

With that said, when companies like Facebook and Twitter open up public APIs, they do so to proliferate their brand. When you allow developers to use their creativivity and time they may produce applications or tools that nobody internally would've dreamed of. I think OAuth is an obvious win Alpaca's growth.

Let me know if an email would help, and what address to send it to.

**Comment by ChemicalRocketeer** [comment]
Sure thing @codebeaulieu, I'd love to hear about it. You can reach me at aaron@alpaca.markets.

**Comment by codebeaulieu** [comment]
@ChemicalRocketeer email sent 👍

**Comment by empireofryan** [comment]
@ChemicalRocketeer I'm interested in building an automated version of Robinhood on the Alpaca platform. I love RH, but I hate how the process is 100% manual. To set a trailing stop loss, for example, a user needs to consistently update the stop loss price throughout the day as a stock changes. With Alpaca, a web interface with a rolling 2% drop trailing stop loss could be programming and switched on by the user. Another feature I'd love to build is to exit positions at the end of trading day then rebuy at market open to avoid after hours swings. Again, with RH one has to manually trigger each trade for each stock to do this, which is very time-consuming and cumbersome. A 'Exit Positions at EOD' could automate this.

Really just the tip of the iceberg, but my idea is to allow users to log in then build a platform for a marginal fee ($20-30 per month) to let them perform all these custom trades. There's also buying when hitting 2x below the standard deviation, buying volatility stocks when the S&P goes down, selling on an above average minute by minute drop just to name a few.

**Comment by samantha-wong** [comment]
+1 From me too! I'm also trying to build something similar in Australia.

**Comment by jtan25** [comment]
I too am waiting for this feature to build a mobile app. The importance of OAuth to me is allowing for my end users to mange their own portfolios.

**Comment by Khanguy** [comment]
+1  What's the status on this?

**Comment by codebeaulieu** [comment]
@Khanguy Its in progress

**Comment by umitanuki** [comment]
Closing this as it's been implemented now.

**Comment by saurabhhey** [comment]
> use the state parameter.

Now they have implemented and i am stuck with the Oauth and I am not able to even simulate the same in postman to build out web app ... If you could share the process for alpaca it will we great

**Comment by saurabhhey** [comment]
> +1 From me too.
> 
> Somewhat related note:
> 
> By the way everyone, did you know Plaid stores your bank credentials somewhere in their database, and then they just use web scraping techniques to log you in and keep your session token refreshed?
> 
> I don't use Plaid because I think that's a little crazy (and it probably violates my banks Terms of Usage thus voiding warranty). And for the same reason, I wouldn't be comfortable giving an app built on top of Alpaca my credentials.
> 
> Another benefit of OAuth are scopes. Not sure what scopes we need, but think of the possibility of limiting what an authorized third party could do. I think there's value in that over giving the third party your Alpaca credentials, which is nearly full access to everything.
> 
> Also, imagine many third party Alpaca apps. If all of them asked for your credentials, then how would you revoke access for one of these apps but not all of them? It's not possible. If you used OAuth, then you can revoke one of these apps while allowing the others to continue connecting.
> 
> Plus, OAuth gives you a nice way to keep track of who you are giving access to and what scopes are you giving them.
