### ISSUE TITLE
data missed in some days

### ISSUE THREAD

**Issue by yiwiz-sai** [alpacahq/Alpaca-API#209]
For example,  QQQ/TQQQ  data missed in 2018-05-02/2018-05-03  includes all min bar data and tick data

https://data.alpaca.markets/v2/stocks/QQQ/bars?start=2018-05-02T00:00:00Z&end=2018-05-02T23:59:59Z&limit=10000&adjustment=all&timeframe=15Min'

https://data.alpaca.markets/v2/stocks/TQQQ/bars?start=2018-05-02T00:00:00Z&end=2018-05-02T23:59:59Z&limit=10000&adjustment=all&timeframe=15Min'

**Comment by gnvk** [comment]
Thank you for reporting this. The missing data has been loaded and should be available now.
