### ISSUE TITLE
Please add 2FA

### ISSUE THREAD

**Issue by elieobeid7** [alpacahq/Alpaca-API#216]
This issue existed before, I'm creating a duplicate.

Please add 2fa via a mobile app or use Twilio API if you want to only send SMS. I'm not in the US so I can't activate 2FA via SMS, Twilio sends SMS worldwide and is very easy to implement.

**Comment by MaxMcArch** [comment]
Hey, @elieobeid7!

We just added TOTP MFA to security settings in your account, and we extend coverage for SMS MFA worldwide.
Please, visit your Alpaca account > Settings > Security to enable it.

Take care!
Max

**Comment by elieobeid7** [comment]
Awesome thanks!
