### ISSUE TITLE
missed bar/trades data 

### ISSUE THREAD

**Issue by yiwiz-sai** [alpacahq/Alpaca-API#225]
missed 'LABU' data in 2016-2-17
missed "QID" data in all time

**Comment by gnvk** [comment]
Thank you for reporting this issue. 

LABU trades & bars were in fact missing for 2016-02-17. I added them. 

Please provide more details for your QID problem. I tried several request for bars/trades for some random dates, and the API returns many of them.

**Comment by yiwiz-sai** [comment]
thanks @gnvk,  I made a mistake when query QID,  the data has no problem, thank you for adding LABU
