### ISSUE TITLE
Fractional Order Requests Not Working

### ISSUE THREAD

**Issue by MaksymKrut** [alpacahq/Alpaca-API#236]
**Describe the bug**
PaperTrading API - https://paper-api.alpaca.markets/v2/orders
As per documentation https://alpaca.markets/docs/trading/fractional-trading/
"notional" or "qty" body parameter takes doubles, like 3.654 or 500.75 from examples from above URL.
But currently non of the body loads from above URL leads to successful order:

Request body:
`{
  "symbol": "AAPL",
  "qty": 3.654,
  "side": "buy",
  "type": "market",
  "time_in_force": "day"
}`
Response:
`{
    "code": 40010001,
    "message": "qty must be integer"
}`

Request body:
`{
  "symbol": "AAPL",
  "notional": 500.75,
  "side": "buy",
  "type": "market",
  "time_in_force": "day"
}`
Response:
`
{
    "code": 40010001,
    "message": "qty is required"
}
`

**To Reproduce**
1. Make POST request to https://paper-api.alpaca.markets/v2/orders with one of the above request bodies.
2. See 422 error with mentioned above response messages.

**Expected behavior**
Making POST request to make Fractional Order returns 200 with successful fractional order creation

**Screenshots**

**Desktop (please complete the following information):**
 - OS: MacOS
 - Tool: Postman

**Comment by MaksymKrut** [comment]
[SOLVED] Please mark as solved. To those who come here from search. If your paper account created before May 2021, reset account and regenerate API keys. Solutions from https://forum.alpaca.markets/t/support-for-fractional-shares/484/50?page=3 helped. Note: current rules for fractional order: `time_in_force: "day", order_class: "simple"`. And "no", bracket orders sadly not supported yet.

**Comment by umitanuki** [comment]
Thanks for the report & update!
