### ISSUE TITLE
Limit order fills regardless of the limit price

### ISSUE THREAD

**Issue by Elangovan4ever** [alpacahq/Alpaca-API#244]
**Describe the bug**
Limit order works like market order

**To Reproduce**
1. Under Paper Trading, Go TSLA symbol page. Current trading price is around $211.
2. Select Buy, Limit, enter quantity 10, enter price $300
3. Preview order and submit. 
4. The order is getting filled at the market price i.e. around $211.
5. Same issue for all symbols on paper trading from the web portal and also by using the alpaca API.

**Expected behavior**
 It supposed to be filled at only $300 which is the limit price. I have tried with other symbols, same issue. This is in paper trading.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser : Microsoft Edge
 - Version: Version 109.0.1518.78 (Official build) (64-bit)

**Additional context**
This is main feature of trading i.e. filling at limit price instead of some random price. Please look at this urgently. thank you!

**Comment by sshcli** [comment]
This is the normal behavior. This is not a bug

**Comment by spazmodius** [comment]
Is this a tracer, to detect whether Aplaca is even looking at issues?

**Comment by sshcli** [comment]
@spazmodius join the Alpaca slack community, they are more active there than here.

**Comment by Elangovan4ever** [comment]
> This is the normal behavior. This is not a bug

Thats strange. I couldn't find this is mentioned in alpaca's guides/api documentations. By any chance, do you have any reference from their docs? It would be difficult to test limit price based algo in this case. IMHO, Paper trading should mimic the live trading, but this one is not.

**Comment by spazmodius** [comment]
["For a buy limit order, if the market price is within your specified limit price, you can expect the order to be filled."](https://alpaca.markets/docs/trading/orders/#limit-order)

**Comment by Elangovan4ever** [comment]
thanks for the comments. I just realized this bug is completely wrong. Obviously, it will execute the order when the limit price is higher than the market price. not sure what I was thinking while raising this as bug. my apologies.
