### ISSUE TITLE
Order History tab shows false (duplicated) orders

### ISSUE THREAD

**Issue by gabokr** [alpacahq/Alpaca-API#245]
**Describe the bug**
Two orders shown (actual) instead one order (expected) in the Order History tab of the [Paper dashboard overview](https://app.alpaca.markets/paper/dashboard/overview).  
I posted 1 long position for MSFT via API, with size 22. The portfolio tab correctly shows just one position of MSFT having size 22. 
The order history is wrong as it shows 2 filled orders with ± 4 min gap between the orders' submission times.

**To Reproduce**
I don't typically see this behaviour and I am not sure if it is reproducible.
The order was posted as a simple limit day order (no brackets, no PT, no SL etc).

**Expected behavior**
I would expect the total quantity of Filled orders be equal to the quantity in the Portfolio.

**Screenshots**
<img width="889" alt="Screenshot 2023-02-16 at 18 56 06" src="https://user-images.githubusercontent.com/11414968/219449852-202c8b2e-4145-402d-bbc1-c7f0cdb80582.png">

**Desktop (please complete the following information):**
 - OS: Mac OS X 13.2.1
 - Browser: chrome
 - Version: 109.0.5414.119

**Additional context**
Unfortunately, I didn't capture the Portfolio tab when the position was still open (got liquidated by my algo).

**Comment by sai-g** [comment]
We do see two different orders (BUY MSFT Qty=22) from the same account, there could be a delay in updating the portfolio screen. Without a portfolio screenshot, it will be challenging to understand the real issue here.

**Comment by gabokr** [comment]
> We do see two different orders (BUY MSFT Qty=22) from the same account, there could be a delay in updating the portfolio screen. Without a portfolio screenshot, it will be challenging to understand the real issue here.

Thanks @sai-g. I reviewed it one more time and realised that the issue was on my end. I didn't see this correctly when I reported, although I checked it twice. Now all clear. No issue with the dashboard. Sorry for false positive!
