### ISSUE TITLE
SEC requires 2-day settlement

### ISSUE THREAD

**Issue by taignehammock** [alpacahq/Alpaca-API#36]
Prior to this morning's trades (sells) my account had about $200 cash available. I sold several positions, now the account shows I have the money from those sells available as cash.

SEC requires 2-day settlement period. Funds from the trades should not be available until Tuesday morning, so the "cash" value should be the same as this morning before I sold (reflected "cash" amount should not update until trades are settled).

![image](https://user-images.githubusercontent.com/8098145/52500432-37f15980-2b9b-11e9-8f66-263ae262bda6.png)

![image](https://user-images.githubusercontent.com/8098145/52500509-67a06180-2b9b-11e9-8c5d-962ca1587bc9.png)

**Comment by ChemicalRocketeer** [comment]
Am I correct that the issue here is not with the amount displayed, but with the use of the word "Cash" to describe unsettled funds?

**Comment by ttt733** [comment]
The 2-day settlement period you're referring to is specifically for cash accounts. At Alpaca, all accounts are margin accounts, so users don't need to account for the T+2 settlement period when figuring out how much they will have available to trade with at a given moment. The only thing that needs to be kept in mind is that cash cannot be withdrawn to a bank account until it has settled. If that's information you think should be available through the API, please open a feature request and it can be discussed there.

**Comment by taignehammock** [comment]
Is "cash_withdrawable"meant to show settled cash? Or is it "buying_power"?
If I use "cash" I'll definitely go over with my buy orders. :)

Thank you!

**Comment by ChemicalRocketeer** [comment]
`cash_withdrawable` is settled cash, yes. `buying_power` is how much money you can currently use for trading.
