### ISSUE TITLE
paper  bars endpoint not found

### ISSUE THREAD

**Issue by ezuhl** [alpacahq/Alpaca-API#38]
I am using the paper endpoint via your go-lang api.

Request:
limit := 5
	param := alpaca.BarListParams{}
	param.Timeframe = "day"
	//param.StartDt = &start
	//param.EndDt = &end
	param.Limit = &limit

	barList ,err  := alpacaClient.ListBarLists([]string{"MMM", "ABT", "ABBV", "ACN"},param)

//https://paper-api.alpaca.markets/v1/bars?limit=5&symbols=MMM%2CABT%2CABBV%2CACN

Response: 
{"code":40410000,"message":"endpoint not found"}

**Comment by ttt733** [comment]
Hello, I've opened an issue for this on the go SDK's repository: alpacahq/alpaca-trade-api-go/issues/13
We can track this on there.

**Comment by ezuhl** [comment]
Thanks!

Ethan
