### ISSUE TITLE
Please install GitHub's Slack integration

### ISSUE THREAD

**Issue by codebeaulieu** [alpacahq/Alpaca-API#39]
As a community member of Alpaca it's hard to get a sense of where issues are without returning to GitHub and checking manually. I think it would like to see GitHub's slack integration installed on Alpaca's Community slack. This would give community members insight into what's being worked on and excitement about items being completed.

The somewhat verbose nature of this GitHub client would give everyone the feeling that "things were in motion".

<img width="992" alt="screen shot 2019-02-12 at 5 47 25 am" src="https://user-images.githubusercontent.com/9411281/52633439-0376e980-2e8a-11e9-935a-6c831e057014.png">

This is an easy win:

https://slack.github.com

**Comment by ttt733** [comment]
Hello, we've currently got issues coming through to our internal Slack, but if this is something that the community would find helpful, I can put updates into the community Slack too. I will add it to the #issues channel later today. If it's too noisy for that channel, I'll give it its own separate channel.
