### ISSUE TITLE
Samplealgo01 does not work

### ISSUE THREAD

**Issue by ehance** [alpacahq/Alpaca-API#41]
There is an error in your sample code.  TypeError: cannot perform __mul__ with this index type: Index
when returning barset.df from _get_prices, defined  line 24 in algo.py

**Comment by umitanuki** [comment]
Can you give us more details about the error? Maybe stacktrace in the console may be helpful.

**Comment by jeichenseerNRX** [comment]
This is pretty clearly outlined in issue 12 on Samplealgo01,
https://github.com/alpacahq/samplealgo01/issues/12

At the end of that issue, user cujo0072 gave a solution which worked for me.
