### ISSUE TITLE
Erroneous data from polygon.io API

### ISSUE THREAD

**Issue by JNAV86** [alpacahq/Alpaca-API#42]
After combing through some of my data returned from polygon historic_agg(), I noticed several symbols that contained some odd data. 

In the response the data for 2019-01-26 seemed to be incorrect, I checked other data sources such as google, yahoo & trading view, and none of them reflected what was seen in my response.

Here are the  possible discrepancies:
close: 241
high: 499
volume: 53566977

Here's one of the responses after testing the request in Insomnia:
{
  "symbol": "AAC",
  "aggType": "daily",
  "map": {
    "o": "open",
    "c": "close",
    "h": "high",
    "l": "low",
    "v": "volume",
    "t": "timestamp",
    "d": "day"
  },
  "ticks": [
    {
      "o": 2.31,
      "c": 2.38,
      "h": 2.505,
      "l": 2.31,
      "v": 137674,
      "t": 1548450000000,
      "d": "2019-1-25"
    },
    {
      "o": 2.35,
      "c": 241,
      "h": 499,
      "l": 2.25,
      "v": 53566977,
      "t": 1548536400000,
      "d": "2019-1-26"
    },
    {
      "o": 2.37,
      "c": 2.22,
      "h": 2.4,
      "l": 2.2,
      "v": 192091,
      "t": 1548709200000,
      "d": "2019-1-28"
    }
  ]
}

I notified polygon.io support to which they mentioned that the v1 API is deprecated and to use v2,
after testing the v2 request this is the response I received:

{
  "ticker": "AAC",
  "status": "OK",
  "queryCount": 4,
  "resultsCount": 3,
  "adjusted": true,
  "results": [
    {
      "v": 137674,
      "o": 2.31,
      "c": 2.38,
      "h": 2.505,
      "l": 2.31,
      "t": 1548392400000,
      "n": 1
    },
    {
      "v": 5.3566977e+07,
      "o": 2.35,
      "c": 241,
      "h": 499,
      "l": 2.25,
      "t": 1548478800000,
      "n": 1
    },
    {
      "v": 192091,
      "o": 2.37,
      "c": 2.22,
      "h": 2.4,
      "l": 2.2,
      "t": 1548651600000,
      "n": 1
    }
  ]
}

Pretty much the same issues as before. Considering the problems with this data, it pretty much means that polygon.io is useless at this point. I was really excited in working with these API's, but I'm very hesitant now. This is a very serious issue and should be addressed ASAP. 

Data is our lifeblood.

**Comment by JNAV86** [comment]
Here are the Polygon requests:

v1: 
https://api.polygon.io/v1/historic/agg/day/AAC?from=2019-01-25&to=2019-01-29&limit=100&unadjusted=true?apiKey=API_KEY

v2: 
https://api.polygon.io/v2/aggs/ticker/AAC/range/1/day/2019-01-25/2019-01-29?apiKey=API_KEY

**Comment by JNAV86** [comment]
Polygon support got back with me today and verified that this data was test data sent out on the weekends from the exchanges. The support team is currently working on cleaning up that data and will inform me when it has been resolved. I'll close this issue once I verify it's been resolved.

**Comment by codebeaulieu** [comment]
What a coinidence,... I literally ran into this exact issue on this same ticker last night.

AAC
close: 241
high: 499

I was pulling all the tickers into my own database that ift a specific critera. Then, for the tickers that fit my criteria I attempted to store the 52 week high/low, average volume and average true range. This ticker (any **many** others) had bad data rendering my Average True Range effort useless.

**Comment by JNAV86** [comment]
> What a coinidence,... I literally ran into this exact issue on this same ticker last night.
> 
> AAC
> close: 241
> high: 499
> 
> I was pulling all the tickers into my own database that ift a specific critera. Then, for the tickers that fit my criteria I attempted to store the 52 week high/low, average volume and average true range. This ticker (any **many** others) had bad data rendering my Average True Range effort useless.

Hopefully they resolve this ASAP, it's holding me up too. I'll inform the community once it's been resolved. Bummer...

**Comment by JNAV86** [comment]
Polygon.io support notified me that the issue has been resolved for the v2 API aggs. I've verified that the erroneous data is in fact no longer in the response.
