### ISSUE TITLE
Bars endpoint ignoring time parameters

### ISSUE THREAD

**Issue by mtcliatt** [alpacahq/Alpaca-API#47]
Steps to reproduce:

`GET https://data.alpaca.markets/v1/bars/day?symbols=AAPL&limit=1&start=2019-02-01&end=2019-02-10`

Response: `{"AAPL":[{"t":1551243600,"o":173.21,"h":175,"l":172.73,"c":174.87,"v":27816083}]}` (from today, which is not in range start-end)

**Comment by Meinerzhagen** [comment]
I am having the same problem. The API completely ignores all time parameters (-start, -end, -after, -until) and always returns a barset ending with the last day during which the market was open. I tried many different timestamp formats for the start and end parameters (e.g., end_dt and end in code example below), but none of them worked.

Python code:
symbol = 'SPXL'
	end_dt = pd.Timestamp('2019-02-28', tz=NY)
	end = end_dt.strftime('%Y-%m-%d')
	print(end)
	barset = api.get_barset(
		symbol,
		'day',
		limit = 1,
		end=end
	)
	bars = barset[symbol]
	for bar in bars:
		mytime = bar.t
		openp = bar.o
		high = bar.h
		low = bar.l
		close = bar.c
		vol = bar.v
		print('Open time {}'.format(mytime))
		print('Open {}'.format(openp))
		print('High {}'.format(high))
		print('Low {}'.format(low))
		print('Close {}'.format(close))
		print('Volume {}'.format(vol))

Response: Note that the date, 2019-03-15, is wrong. I expected to see 2019-02-28.
2019-02-28
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): data.alpaca.markets:443
DEBUG:urllib3.connectionpool:https://data.alpaca.markets:443 "GET /v1/bars/day?symbols=SPXL&limit=1&end=2019-02-28 HTTP/1.1" 200 79
Open time 2019-03-15 00:00:00-04:00
Open 45.95
High 46.75
Low 45.85
Close 46.33
Volume 5508805

**Comment by umitanuki** [comment]
Please send start and end parameter with strict RFC3339 format (i.e. "2019-02-28T00:00:00Z") even if it is day query. We are aware of the issue and hoping to loosen the rule to be more flexible, but at this point this is what it is.

**Comment by mtcliatt** [comment]
Will you open an issue for tracking?

**Comment by umitanuki** [comment]
Sure, we can open an issue for improvements. This issue itself is to resolve the user confusion for the current design (which is not optimal).

**Comment by x777** [comment]
Looks like this problem still presents? Can't fetch data from a particular range.
