### ISSUE TITLE
Total P&L on the web dashboard seems wrong

### ISSUE THREAD

**Issue by trobrock** [alpacahq/Alpaca-API#48]
I've invested a total of $1k in my account, I'm currently at $1009.20. I would expect a Total p/l of 0.92% but it currently shows 1.34%.

<img width="1552" alt="screen_shot_2019-03-01_at_9_14_30_am" src="https://user-images.githubusercontent.com/94053/53643678-abb6dd00-3c02-11e9-8082-845b2479c501.png">

**Comment by evanhft** [comment]
Verified that the total profit/loss as currently displayed is reflects the time-weighted return (https://www.investopedia.com/terms/t/time-weightedror.asp) and is correctly calculated. We will be updating the dashboard due to an abundance of confusion with this reported value.
