### ISSUE TITLE
Incorrect account balance

### ISSUE THREAD

**Issue by trobrock** [alpacahq/Alpaca-API#49]
This morning I checked around 6am EST and my account balance was at $1140.812, which seemed way too high (my algo isnt that good), but then an hour later it was down to $1007.05.

Was there an issue causing this? Or something else?

**Comment by trobrock** [comment]
After market open it dropped to $999, which based on the numbers I saw at close yesterday is the first number that really makes sense. I'm wondering if something weird is going on after hours?

**Comment by ttt733** [comment]
Was this checking with the dashboard, or via the API's account endpoint? We're aware of and are working on fixing some dashboard issues, but if the API is returning incorrect results we will look into it.

**Comment by umitanuki** [comment]
@trobrock we have updated the dashboard balance display in many ways. Let us know if you still see that issue, since I don't think there was a particular change to address this pre-market issue but it might be fixed along with others. We are eager to improve it, so appreciate your help. Thanks!
