### ISSUE TITLE
Open orders won't cancel (on paper act)

### ISSUE THREAD

**Issue by hainesmatt** [alpacahq/Alpaca-API#51]
I've got three limit sell orders that my algo placed. I cannot cancel them manually using manual-alpaca,.py, and I can't cancel them using the "cancel all orders" function in the dashboard. For the latter, I get a message saying the three have been canceled, but they remain. This is after hours btw.

I'm able to add a market buy order after-hours, and then cancel that one with no problem. It's only these three that appear to be the problem.

The order info:

  # symbol      qty    side    status   client id
  0 GOSS        138    sell       new  strat02_bL_2019-03-04T20:57:31.633665+00:00
  1 AVDR        268    sell       new  strat02_bL_2019-03-04T20:57:29.845589+00:00
  2 NFE         199    sell       new  strat02_bL_2019-03-01T20:58:17.051648+00:00

**Comment by umitanuki** [comment]
There have been some instances that order status gets stuck with "new" and cancel doesn't work either. This is mainly in the paper simulator issue and we are working on improving it. That said, I can see those three orders are marked as "canceld" by now so closing. Let us know if you still see the issue.

**Comment by hainesmatt** [comment]
Another data point: I was able to cancel them during market hours the next day, but not overnight. Canceling in after-hours hadn’t been an issue before. Thanks.

**Comment by umitanuki** [comment]
I can see what's happening but let us get back to you.

**Comment by umitanuki** [comment]
Was it from the trading API or dashboard? Do you know what time of the day it didn't work?

**Comment by hainesmatt** [comment]
I believe I tried it from both the api and the dashboard. It would have been after hours. This was a week or two ago so I don’t really remember.

**Comment by akaniklaus** [comment]
I have the same issue. Can't cancel them on paper trader after hours.

**Comment by CamDHall** [comment]
Is there an update on this issue? I also cannot cancel my open orders.

**Comment by t-shah** [comment]
Seeing the same issue (cancelling after hours in the web gui)...
