### ISSUE TITLE
Endpoint to return day trade count

### ISSUE THREAD

**Issue by codebeaulieu** [alpacahq/Alpaca-API#59]
I assume that Alpaca is maintaining a count of our day trades. It would be super convenient as well as reassuring to **not** have to keep track of this on my end. 

Please create an endpoint that returns how many round trips / day trades we have on our accounts.

**Comment by umitanuki** [comment]
This is coming actually. Will keep you posted.

**Comment by bdowling** [comment]
Closing as duplicate of issue #11. 

Thanks for the suggestion.

**Comment by codebeaulieu** [comment]
Thanks @bdowling I actually searched for both “daytrade” and “count” before posting this but didn’t find any results. My bad! 😬
