### ISSUE TITLE
Add price of purchase

### ISSUE THREAD

**Issue by gjtorikian** [alpacahq/Alpaca-API#65]
If I place a market order like so:

```go
	buyOrderRequest := alpaca.PlaceOrderRequest{
		AccountID:   account.ID,
		AssetKey:    &stock,
		Qty:         quantity,
		Side:        alpaca.Buy,
		Type:        alpaca.Market,
		TimeInForce: alpaca.Day,
	}

	resp, err = alpacaClient.PlaceOrder(buyOrderRequest)
```

It would be nice to get data on what the actual buy price was. As it stands, although the market order is filled instantly, there is no guarantee that it's at the price I expected and that slippage did not occur. This would also be advantageous for limit orders: I place a `limit_order`, but I would like to know from the resulting [Order entity](https://docs.alpaca.markets/api-documentation/web-api/orders/#order-entity) what that price was!

**Comment by bdowling** [comment]
Order execution is an asynchronous operation.  If you later query the order API for the order ID you can see that it includes a `filled_avg_price` that should answer your question.  The streaming API will also return this data and is good to utilize for faster execution details.

BTW if you in the future your issues are with a particular client library, posting the issues in the language repo may be better.

Thanks,
Brian

**Comment by codebeaulieu** [comment]
I ran into this before but I think the issue is that what is being returned isn't your _**filled**_ order, its returning your new **_pending_** order. Even if it was filled immediately.

In other words, rather than waiting for a response that your order has been filled, its a receipt or a way of communicating that your order was successfully received.

Maybe I'm wrong on this, this is just how I think about this endpoint.

**Comment by gjtorikian** [comment]
> Maybe I'm wrong on this, this is just how I think about this endpoint.

You're both right! 😆 

Sounds like I need to hold on to the `order_id` until the order is `fulfilled`, and then check the `filled_avg_price`.

> BTW if you in the future your issues are with a particular client library, posting the issues in the language repo may be better.

Sorry about that. My question was language idempotent but I felt like this example showed what I was saying.
