### ISSUE TITLE
authentication failed when using  polygon webSocket

### ISSUE THREAD

**Issue by herbertchow214** [alpacahq/Alpaca-API#68]
Using REST with my key id worked,
  curl https://api.polygon.io/v1/last_quote/stocks/AAPL?key_id=XXX worked
{"status":"success","symbol":"AAPL","last":{"askprice":189.22,"asksize":1,"askexchange":19,"bidprice":189.21,"bidsize":2,"bidexchange":19,"timestamp":1557862846384}}

however using webSocket  end authentication msg {"action":"auth","params":"XXX"} to wss://socket.polygon.io/stocks,
  I received authentication error {"ev":"status","status":"error","message":"authentication failed"}]

**Comment by ttt733** [comment]
For Polygon streaming, at the moment you will need to use NATS, as Alpaca keys are not authenticated properly on their websocket cluster. The NATS cluster is unfortunately undocumented, but you can see examples of how to connect in our SDKs - for example, here: https://github.com/alpacahq/alpaca-trade-api-python/blob/master/alpaca_trade_api/polygon/stream.py

**Comment by bdowling** [comment]
For anyone finding this old issue through a search, the websocket interface for Polygon is now supported, and you can use one of our many SDKs to access it.  

Note that if you are attempting to access it directly, the URI for our customers using Alpaca KEY_ID is `wss://alpaca.socket.polygon.io/stocks`

**Comment by jeffwlandry** [comment]
Using c# api library. I am using wss://alpaca.socket.polygon.io/stocks from environment.  Worked fine earlier this week.  This afternoon I get the authentication failed message.
                polygonStream = alpacaEnvironment.GetPolygonStreamingClient(accountID);
                polygonStream.OnError += polygonSocketError;
                polygonStream.SocketOpened += polygonSocketOpened;
                polygonStream.SocketClosed += polygonSocketClosed;
                polygonStream.Connected += polygonSocketConnected;
                AuthStatus auth = await polygonStream.ConnectAndAuthenticateAsync(cancellationTokenStreamSocketError);
all the other sockets open.

Any suggestions appreciated.

Jeff

**Comment by maciej-gorny** [comment]
Same here. It worked fine with a Java client for months, then all of a sudden, last week, authorization (SSL) errors. Switched to python thinking it's be better supported since it's not third party, but same happened: it was fine for a few days, then out of nowhere, with no changes on my end, auth errors again this morning.
