### ISSUE TITLE
Canceled/Filled order at same time

### ISSUE THREAD

**Issue by cheilaa90** [alpacahq/Alpaca-API#71]
**Date and time on which the issue occurred:** 06/06/2019
**Whether or not you were using the paper trading API:** Paper API
**What you were trying to do:** I had placed a Buy Order during a regular Paper Trading
**What happened:** I have developed an algorithm to trade through Alpaca and I am using my paper account for now. Last week, while I was doing some tests, I noticed that Alpaca filled and canceled a buy order at the same time (see image). I would like to understand why this happened to move forward to the Live Trading.

![alpaca-error](https://user-images.githubusercontent.com/51682908/59236771-98ce8400-8bc5-11e9-9287-8f6e7eba6df1.jpg)

**Comment by bdowling** [comment]
Closing this issue, as we addressed this through your support@alpaca.markets inquiry.  Updates to the platform were rolled out this week that should prevent a recurrence.

Thank you!
