### ISSUE TITLE
Discrepancy between stocks Polygon knows and stocks Alpaca knows about

### ISSUE THREAD

**Issue by gjtorikian** [alpacahq/Alpaca-API#79]
It seems that Polygon and Alpaca have two different stock sets. `YETI` is one such ticker. For example, I can get data through Polygon's API:

```
curl "https://api.polygon.io/v1/open-close/YETI/2019-07-11
{"status":"OK","from":"2019-07-11T03:30:00Z","symbol":"YETI","open":33.65,"high":33.93,"low":32.87,"close":33.82,"afterHours":33.96,"volume":1964895}
```

But not Alpaca:

```
curl "https://api.alpaca.markets/v2/assets/YETI"
{"code":40410000,"message":"asset not found for YETI"}
```

I found about nine stocks like this: 

```
LGF.A
DBI
VIV
HRS
VRRM
CBD
HRS
GOL
YETI
SITC
VIV
DBI
LLL
```

Is there a specific reason for this difference?

**Comment by gjtorikian** [comment]
Are there any updates here?

**Comment by umitanuki** [comment]
It was due to our asset master data. YETI is now tradable and we are looking into other data now.
