### ISSUE TITLE
missing deposits (CSR) with get_acivities API

### ISSUE THREAD

**Issue by corakwue** [alpacahq/Alpaca-API#84]
Some completed ACH deposits to the brokerage account  (visible on banking>history via the dashboard) are not reported with activities API.

```python
import alpaca_trade_api as tradeapi

api = tradeapi.REST('<key_id>', '<secret_key>', api_version='v2') 
api.get_activities(activity_type=["TRANS"]) # missing some deposits
```

**Note:** setting `date` or pagination doesn't address this.

**Comment by umitanuki** [comment]
Could you send your account id or email to support@alpaca.markets or send it to Hitoshi in the community slack

**Comment by umitanuki** [comment]
Thanks, working on it
