### ISSUE TITLE
Add multi-conditional orders e.g. bracket orders, OCOs

### ISSUE THREAD

**Issue by evanhft** [alpacahq/Alpaca-API#9]
Add advanced orders that allow for multiple conditions such as:

1) stop limit entry
2) profit target exit order
and/or
3) stop loss exit order

**Comment by codebeaulieu** [comment]
Would definitely like to see this implemented soon.

**Comment by kanendosei** [comment]
Really interested in "bracket" ordering, where I can use the Python API to write to this call:
`submit_order(symbol, qty, side, type, time_in_force, limit_price=None, stop_price=None, client_order_id=None)`

And set the limit_price, stop_price at once, such that:
`submit_order('AAPL', 100, 'buy', 'market', 'gfd', 174.00, 172.00)`

Would mean:
1. Buy 100 shares of AAPL at the current market price ($173.40 as I write this)
2. If AAPL price rises above $174, sell AAPL  [limit sell]
3. If AAPL price drops below $172, sell AAPL [stop]

**Comment by garyha** [comment]
Bracket orders make my algos profitable elsewhere.

**Comment by quada** [comment]
is there an update on this? The Alpaca team has been saying "the next release" for months now

**Comment by ZippeyKeys12** [comment]
Bracket, OCO and OTO were added, for any other requests, make a new issue
