### ISSUE TITLE
no daytrade buying power and other issue

### ISSUE THREAD

**Issue by wjg59701** [alpacahq/Alpaca-API#92]
Hello,

When I use the python API on my paper account I receive an error: No Daytrade buying power. 

Also, orders that I paper trade on the website manually will complete, but then when I access throuigh the API the account does not reflect a change.

Any ideas?

**Comment by bdowling** [comment]
If your account has been flagged as day trading, PDT, it must be above 25k equity for DT buying power to be calculated.   You can reset your paper account in the system to set a higher starting equity, be sure to renew your API keys and keep them in sync with the paper account to make sure you are updating the same account.

If you need further support and to better support you on your particular account issues, please contact us at support@alpaca.markets.
