### ISSUE TITLE
insufficient day trading buying power (paper trading)

### ISSUE THREAD

**Issue by suedadam** [alpacahq/Alpaca-API#98]
I was trying to purchase GME for ~$5 which provided me with the error "insufficient day trading buying power".

This happened through the API and through the online website. 

This happened at ~10:51AM PST. 

<img width="992" alt="image" src="https://user-images.githubusercontent.com/3879307/72462080-1b837700-3785-11ea-8001-14ab867df4f7.png">

**Comment by umitanuki** [comment]
Can you check your Account API response for daytrading_buying_power?

**Comment by ZippeyKeys12** [comment]
This means that you've run out of daytrading buying power, which is calculated as part of the Day Trade Margin Call (DTMC) Protection. The calculation is `daytrading_buying_power = 4 * (last_equity - last_maintenance_margin)` where you can get all these values from your account info. For example, if your `last_maintenance_margin` was greater than your `last_equity`, then you'll have a `daytrading_buying_power` of zero. Both of these are calculated at end of the last trading day, so closing overnight positions will not add to your daytrading buying power.

As for what your maintenance margin is, see the following table, where this is applied to each security held.
| Position Side | Condition | Margin Requirement |
| ------------- | --------- | ---------------------|
| Long | Share Price < $2.50 | 100% of EOD market value |
| Long | Share Price ≥ $2.50 | 30% of EOD market value |
| Long | 2x Leveraged ETF | 60% of EOD market value |
| Long | 3x Leveraged ETF | 90% of EOD market value |
| Short | Share Price < $5.00 | Greater of $2.50/share or 100% |
| Short | Share Price ≥ $5.00 | Greater of $5.00/share or 30% |
